1st Commit - In-Memory-App
ReinisLubins/flight-planner pull request #1
Opened 2022-04-13 17:56 UTC by ReinisLubins

2022-05-02 17:46 UTC, NilsKula requested changes

2022-05-02 17:46 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/AirportAndFlight/AddFlightRequest.java
> +    @Valid
šis jau šķiet lieks? 🤔

2022-05-02 17:46 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/AirportAndFlight/PageResult.java
> +public class PageResult<T> {
<T> labi ka šis 👍

2022-05-02 17:46 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/RestServices/Controllers/AdminFlightController.java
> +    public synchronized Flight fetchFlight(@PathVariable int id) {
šeit jau notiek tik data fetching, synchronized īsti nav vajadzīgs

2022-05-02 17:46 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/RestServices/FlightRepository.java
> +    private boolean strangeDates(Flight flight) {
varētu labāk `invalidDates()` strange īsti nepavēsta ka nederīgi dati 😄

2022-05-02 17:46 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/RestServices/FlightRepository.java
> +    public synchronized Flight addFlight(AddFlightRequest addFlightRequest) {
un tev jau controliera līmenī synchronized, domāu ka labāk tad vienā vietā tur vai te

2022-05-02 17:46 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/RestServices/FlightRepository.java
> +        for (Flight flight : flights) {
labāk izmanto `.stream().filter().map()` sanāks daudz īsāk un smukāk

2022-05-02 17:46 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/RestServices/FlightRepository.java
> +        for (Flight flight : flights) {
šeit arī `.stream()` labāk

2022-05-02 17:46 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/RestServices/FlightRepository.java
> +            if (listFlight.getFrom().getAirport().equals(searchFlightsRequest.getFrom())
šo varētu arī potenciāli `Flight` klasē ienest `flightMatches()` piemēram

2022-05-03 20:38 UTC, NilsKula requested changes
vēl tik mazi labojumi, ar stream uzreiz daudz lasāmāk 👍

2022-05-03 20:38 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/RestServices/Controllers/AdminFlightController.java
> -    public synchronized Flight addFlight(@Valid @RequestBody AddFlightRequest addFlightRequest) {
bez synchronized varēja iztikt jau tik pie fetchFLights, kur nenotiek nekāds datu update, šķiet šeit jau vairs neiziet testi? 🤔

2022-05-03 20:38 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/AirportAndFlight/Flight.java
> +    public static boolean searchedFlightsAreEqual(SearchFlightsRequest searchFlightsRequest, Flight flight) {
pareizi šeit ieliki, bet šo nevajag kā static jo veic pārbaudi uz konkrētu, tādēļ nevajag arī padot `Flight` objektu
vietā kur izsauc sanāktu `flight.searchedFlightsAreEqual(searchFlightsRequest)`

2022-05-03 20:38 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/RestServices/FlightRepository.java
> +                .filter((Flight flight) -> flight.getId() == id).findFirst()
`.filter(flight -> flight.getId() == id).findFirst()`

2022-05-03 20:38 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/RestServices/FlightRepository.java
>          for (Flight listFlight : flights) {
arī šeit stream

2022-05-04 09:19 UTC, ReinisLubins commented on src/main/java/io/codelex/flightplanner/RestServices/Controllers/AdminFlightController.java
> -    public synchronized Flight addFlight(@Valid @RequestBody AddFlightRequest addFlightRequest) {
es atstāju pie addflight un delete flight jo testā tas notiek vienlaicīgi, bet fetchFlight testa netiek pielietots, tapēc noņēmu

2022-05-04 12:04 UTC, NilsKula approved these changes
👍 
izlabo to mazo lieto `searchedFlightsAreEqual()` mewtodē un mergo iekšā

2022-05-04 12:04 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/AirportAndFlight/Flight.java
> +        return Flight.this.getFrom().getAirport().equals(searchFlightsRequest.getFrom())
`Flight.this` šī daļa ir lieki
is all you need `getFrom().getAirport().equals(searchFlightsRequest.getFrom())`

2022-05-04 12:04 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/RestServices/Controllers/AdminFlightController.java
> -    public synchronized Flight addFlight(@Valid @RequestBody AddFlightRequest addFlightRequest) {
jap, sorry, vainīgs, ne tajā rindiņā iekomentēju 😬

2022-05-04 12:09 UTC, merged